name: Deploy para EC2

on:
  push:
    branches:
      - main  # Só executa quando houver push na main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar o Script de Deploy no Runner
        run: |
          echo '#!/bin/bash' > deploy.sh
          echo 'cd /home/ubuntu/Desculp.AI' >> deploy.sh
          echo 'git pull origin main' >> deploy.sh
          echo 'npm install' >> deploy.sh
          echo 'pm2 restart desculpai' >> deploy.sh
          chmod +x deploy.sh

      - name: Configurar Chave SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Aceitar a Chave SSH da EC2 Automaticamente
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Enviar Script de Deploy para EC2
        run: |
          scp -i deploy_key.pem deploy.sh ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/deploy.sh

      - name: Executar o Deploy na EC2
        run: |
          ssh -i deploy_key.pem ubuntu@${{ secrets.EC2_HOST }} "bash ~/deploy.sh"