name: Deploy para EC2

on:
  push:
    branches:
      - main  # Executa apenas quando houver push na main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar SSH para EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Conectar na EC2 e atualizar o código
        run: |
          ssh -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/Desculp.AI
            
            # Configurar SSH para acessar o GitHub dentro da EC2
            mkdir -p ~/.ssh
            echo "${{ secrets.G_SSH_KEY }}" > ~/.ssh/id_ed25519_github
            chmod 600 ~/.ssh/id_ed25519_github
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            
            # Usar a chave SSH do GitHub para fazer git pull
            GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519_github" git pull origin main
            
            # Instalar dependências e reiniciar o servidor
            npm install
            pm2 restart desculpai
          EOF