name: Deploy para EC2

on:
  push:
    branches:
      - main  # Executa apenas quando houver push na main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem

      - name: Aceitar a Chave SSH da EC2 Automaticamente
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy usando Rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /home/ubuntu/Desculp.AI/
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ubuntu
          remote_key: "${{ secrets.EC2_SSH_KEY }}"

      - name: Executar o Deploy na EC2
        run: |
          ssh -i ~/.ssh/deploy_key.pem ubuntu@${{ secrets.EC2_HOST }} "cd /home/ubuntu/Desculp.AI && npm install && pm2 restart desculpai"